### ISSUE TITLE
關於程式授權

### ISSUE THREAD

**Issue by kiang** [lycheetw/KaohsiungDengueMap#1]
其實已經做了衍生版本 http://kiang.github.io/TainanDengueMap/ and http://kiang.github.io/TainanDengueMap/taiwan/

只是剛剛熊熊想到，你的程式並沒有標示授權方式，也許可以放一個 LICENSE  檔案聲明希望使用的授權？感謝 :)

**Comment by lycheetw** [comment]
謝謝提醒
我將以MIT方式授權

台南今天疫情嚴重阿，能幫上點忙真是太好了

**Comment by kiang** [comment]
感謝 :)
